### ISSUE TITLE
cloud sdk 404 errors causing cache to be disabled

### ISSUE THREAD

**Issue by trevjonez** [tehlers/gradle-gcs-build-cache#1]
Every handful of builds I am seeing issues that look like this:

`The remote build cache was disabled during the build due to errors.`
with a trimmed stack that is roughly:
```
org.gradle.caching.BuildCacheException: Unable to load 'cache_key' from Google Cloud Storage bucket 'bucket_name'.
at net.idlestate.gradle.caching.GCSBuildCacheService.load(GCSBuildCacheService.kt:86)

Caused by: com.google.cloud.storage.StorageException: 404 Not Found
No such object: bucket_name/cache_key
at com.google.cloud.storage.spi.v1.HttpStorageRpc.translate(HttpStorageRpc.java:226)

Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 404 Not Found
```

Given that a 404 is a simple not found that seems it may be an eventual consistency type issue, should we special case the catch to check for that 404 and simple return false rather than re-throwing the BuildCacheException?

**Comment by trevjonez** [comment]
https://github.com/googleapis/google-cloud-java/issues/3402

**Comment by kartikisharma-qz** [comment]
@trevjonez I encountered similar issues. My only confusion is doesn't this load of `cache_key` imply that the `cache_key` matched up to an existing one?

**Comment by trevjonez** [comment]
I completely agree that it makes no sense, give that issue I linked a look, fairly certain this is just a manifestation of that.
