### ISSUE TITLE
Make credentials file optional, use GCP Application Default Credentials

### ISSUE THREAD

**Issue by nhoughto** [tehlers/gradle-gcs-build-cache#4]
At the moment the credentials json file is required, and hard coded to use the service account credential type, it would be good if when the file parameter is omitted it uses the standard GCP ADC lookup process to locate credentials, so can use the Compute Engine role etc if found.

https://cloud.google.com/docs/authentication/getting-started

**Comment by nhoughto** [comment]
Change proposed in https://github.com/tehlers/gradle-gcs-build-cache/pull/5

**Comment by tehlers** [comment]
Fixed in #5
